# This file was generated by GoReleaser. DO NOT EDIT.
cask "jsawn" do
  name "jsawn"
  desc "Interactive JSON viewer for the terminal"
  homepage "https://github.com/aryankumar07/jsawn"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jsawn"

  on_macos do
    on_intel do
      url "https://github.com/aryankumar07/jsawn/releases/download/v#{version}/jsawn_Darwin_x86_64.tar.gz",
        verified: "github.com/aryankumar07/jsawn"
      sha256 "3924ee3923cd540fd0c29e219c354e8f1fce805bb80808495b4a1234eda838db"
    end
    on_arm do
      url "https://github.com/aryankumar07/jsawn/releases/download/v#{version}/jsawn_Darwin_arm64.tar.gz",
        verified: "github.com/aryankumar07/jsawn"
      sha256 "c7bf177918b8e3714748d122cfb4183e1a8c21f96b91aa2c38df703f4db3e23a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/aryankumar07/jsawn/releases/download/v#{version}/jsawn_Linux_x86_64.tar.gz",
        verified: "github.com/aryankumar07/jsawn"
      sha256 "26c6ae7d09b9acb4d8bbf42b09e088768b76bf05f4cc88c362797c56de8e08e4"
    end
    on_arm do
      url "https://github.com/aryankumar07/jsawn/releases/download/v#{version}/jsawn_Linux_arm64.tar.gz",
        verified: "github.com/aryankumar07/jsawn"
      sha256 "dea8c11a49d394edc63ce10af453a4a6f97e61050272a828c3bbd8e085e09094"
    end
  end

  # No zap stanza required
end
