# This file was generated by GoReleaser. DO NOT EDIT.
cask "jsawn" do
  name "jsawn"
  desc "Interactive JSON viewer for the terminal"
  homepage "https://github.com/aryankumar07/jsawn"
  version "0.2.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jsawn"

  on_macos do
    on_intel do
      url "https://github.com/aryankumar07/jsawn/releases/download/v#{version}/jsawn_Darwin_x86_64.tar.gz",
        verified: "github.com/aryankumar07/jsawn"
      sha256 "efc7beb68c5a9db231e29a5fbbb7e6655248fb8903bdf561f18d1fe969a998ab"
    end
    on_arm do
      url "https://github.com/aryankumar07/jsawn/releases/download/v#{version}/jsawn_Darwin_arm64.tar.gz",
        verified: "github.com/aryankumar07/jsawn"
      sha256 "e3bc244d13cf86d1d869176de575c7a9952714a2249af3c42762744862546e6b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/aryankumar07/jsawn/releases/download/v#{version}/jsawn_Linux_x86_64.tar.gz",
        verified: "github.com/aryankumar07/jsawn"
      sha256 "76a45f1b83e89821c5c0c695ccde4df1675cbfb4dd05012cba0903c59138a4f3"
    end
    on_arm do
      url "https://github.com/aryankumar07/jsawn/releases/download/v#{version}/jsawn_Linux_arm64.tar.gz",
        verified: "github.com/aryankumar07/jsawn"
      sha256 "1452bdf1cf3cc3a183cc2e0dd204760e098e4be3f6a5110c6a5a43a25869d570"
    end
  end

  # No zap stanza required
end
