# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jsawn < Formula
  desc "Fast JSON parser and query tool"
  homepage "https://github.com/aryankumar07/jsawn"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aryankumar07/jsawn/releases/download/v0.1.0/jsawn_Darwin_x86_64.tar.gz"
      sha256 "aac751d73fa84ed35c3d1e53fbfc66f4fcb416f56d37d71d652ad5db59a3a20a"

      def install
        bin.install "jsawn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aryankumar07/jsawn/releases/download/v0.1.0/jsawn_Darwin_arm64.tar.gz"
      sha256 "694c5012d620cc1411792d564292390cdf6722a4b9bb7cd29ce773ebc0904da7"

      def install
        bin.install "jsawn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aryankumar07/jsawn/releases/download/v0.1.0/jsawn_Linux_x86_64.tar.gz"
      sha256 "36f9646d53f2138519874ae58a105d6abe00c3e40a093cebac0d9735842d97c9"
      def install
        bin.install "jsawn"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/aryankumar07/jsawn/releases/download/v0.1.0/jsawn_Linux_armv6.tar.gz"
      sha256 "f935b001c7e804c628e1e78b4a656df8082353d9c41ca836d4170a698a87a210"
      def install
        bin.install "jsawn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aryankumar07/jsawn/releases/download/v0.1.0/jsawn_Linux_arm64.tar.gz"
      sha256 "e6fc91a8b77668ef1685c71938db66a0b84b5f8dc92911d660f966d8eae42b14"
      def install
        bin.install "jsawn"
      end
    end
  end

  test do
    system "#{bin}/jsawn --version"
  end
end
