# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jsawn < Formula
  desc "Fast JSON parser and query tool"
  homepage "https://github.com/aryankumar07/jsawn"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aryankumar07/jsawn/releases/download/v0.1.0/jsawn_Darwin_x86_64.tar.gz"
      sha256 "f7b21821762d41929c33a9a16606ccff9500aabbafc4dfef9748fd0dfc12c386"

      def install
        bin.install "jsawn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aryankumar07/jsawn/releases/download/v0.1.0/jsawn_Darwin_arm64.tar.gz"
      sha256 "57cdf0f0c7799c6d83203734564505259c6f1e4011da2a588d5c98e821155272"

      def install
        bin.install "jsawn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aryankumar07/jsawn/releases/download/v0.1.0/jsawn_Linux_x86_64.tar.gz"
      sha256 "8b9f15583f66b6b259a39a2403a1a866163835daf505f1916bbc51b8fb3759e6"
      def install
        bin.install "jsawn"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/aryankumar07/jsawn/releases/download/v0.1.0/jsawn_Linux_armv6.tar.gz"
      sha256 "4f5f360f50e4bcdb8213098535f66b4cf7036bed0ff593f0db98d83a4eee62a1"
      def install
        bin.install "jsawn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aryankumar07/jsawn/releases/download/v0.1.0/jsawn_Linux_arm64.tar.gz"
      sha256 "18b599889b3bc4cee4748dc9c107c9ee55247b6033129124de1acabdf763df0d"
      def install
        bin.install "jsawn"
      end
    end
  end

  test do
    system "#{bin}/jsawn --version"
  end
end
